
spring:
  application:
    name: api-service
  datasource:
    url: jdbc:mysql://localhost:3306/kube_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.format_sql: true
    show-sql: true

logging:
  level:
    com.zaxxer.hikari: WARN
    org.hibernate.orm.deprecation: ERROR
    org.hibernate.orm.connections.pooling: WARN
    root: INFO

server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8081