spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: testuser
    password: testpass

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest



# RabbitMQ event publishing configuration
rabbitmq:
  exchange:
    name: crud-events-exchange
  routing:
    key:
      prefix: crud.events