spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: testuser
    password: testpass

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest



# RabbitMQ event publishing configuration
rabbitmq:
  exchange:
    name: crud-events-exchange
  routing:
    key:
      prefix: crud.events

metrics:
  distribution:
    percentiles-histogram:
      http:
        server:
          requests: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    root: debug
    org.springframework.amqp: info
  file:
    name: crud-logs.log
  logstash:
    enabled: false
    destination: logstash:3100
    level: OFF  # Set to ALL to enable, OFF to disable
